project:
  type: website

website:
  title: "Hidden Orders"
  navbar: 
    left:
      - href: analysis.qmd
        text: Home
      - about.qmd
      - index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



