project:
  type: website

website:
  title: "Hidden Security Orders"
  navbar: 
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - analysis.qmd
      - sources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



